-- Schema for SQLite3 database.

BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS names (
    id   INTEGER  PRIMARY KEY AUTOINCREMENT,
    val  TEXT     NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS primes (
    id   INTEGER  PRIMARY KEY AUTOINCREMENT,
    val  INTEGER  NOT NULL UNIQUE
);

COMMIT;
